
import { Inter } from 'next/font/google'
import Nav from '@/components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/sketchy/bootstrap.min.css" />
      
      </head>
      <body className={inter.className}>
        <Nav/>
        
        {children}</body>
    </html>
  )
}
